DROP DATABASE picme;
TRUNCATE USUARIO;
CREATE DATABASE picme;
USE picme;

-- Criação da tabela Usuario
CREATE TABLE USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50),
    CPF VARCHAR(100),
    EMAIL VARCHAR(100),
    SENHA VARCHAR(100),
    DATA_NASCIMENTO DATE,
    AUTENTICADO BOOL,
    CELULAR VARCHAR(20),
    DATA_CADASTRO DATE,
    TIPO_USUARIO VARCHAR(20),
    TOKEN_SOLICITACAO VARCHAR(100)
);

-- Criação da tabela Tema
CREATE TABLE TEMA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50)
);

-- Criação da tabela TemasUsuario
CREATE TABLE USUARIO_TEMAS (
  USUARIOS_ID INT,
  TEMAS_ID INT,
  PRIMARY KEY (USUARIOS_ID, TEMAS_ID),
  FOREIGN KEY (TEMAS_ID) REFERENCES TEMA(ID),
  FOREIGN KEY (USUARIOS_ID) REFERENCES USUARIO(ID)
);

-- Criação da tabela Evento
CREATE TABLE EVENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATA_REALIZACAO DATE,
    STATUS_EVENTO VARCHAR(20),
    FK_FOTOGRAFO INT,
    FK_TEMA INT,
    FK_CLIENTE INT,
    VALOR DECIMAL(10, 2),
    AVALIACAO INT,
    FOREIGN KEY (FK_FOTOGRAFO) REFERENCES USUARIO(ID),
    FOREIGN KEY (FK_TEMA) REFERENCES TEMA(ID),
    FOREIGN KEY (FK_CLIENTE) REFERENCES USUARIO(ID)
);

-- Criação da tabela Endereco
CREATE TABLE ENDERECO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ESTADO VARCHAR(50),
    CIDADE VARCHAR(50),
    CEP VARCHAR(10),
    BAIRRO VARCHAR(50),
    LOGRADOURO VARCHAR(100),
    NUMERO VARCHAR(10),
    COMPLEMENTO VARCHAR(100),
    FK_EVENTO INT,
    FOREIGN KEY (FK_EVENTO) REFERENCES EVENTO(ID)
);

-- Criação da tabela Album
CREATE TABLE ALBUM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(100),
    DESCRICAO VARCHAR(100),
    FK_FOTOGRAFO INT,
    FK_TEMA INT,
    FOREIGN KEY (FK_FOTOGRAFO) REFERENCES USUARIO(ID),
    FOREIGN KEY (FK_TEMA) REFERENCES TEMA(ID)
);

-- Criação da tabela Imagem
CREATE TABLE IMAGEM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CAMINHO VARCHAR(200),
    DESCRICAO VARCHAR(100),
    TIPO VARCHAR(100),
    FK_ALBUM INT,
    FOREIGN KEY (ID) REFERENCES USUARIO(ID),
    FOREIGN KEY (FK_ALBUM) REFERENCES ALBUM(ID)
);

-- Tabela Tag
CREATE TABLE TAG (
  ID INT PRIMARY KEY,
  NOME VARCHAR(100)
);

-- Tabela TagsImagem
CREATE TABLE TAG_IMAGEM (
  ID_IMAGEM INT,
  ID_TAG INT,
  PRIMARY KEY (ID_IMAGEM, ID_TAG),
  FOREIGN KEY (ID_IMAGEM) REFERENCES IMAGEM(ID),
  FOREIGN KEY (ID_TAG) REFERENCES TAG(ID)
);

-- Tabela InteressesTags
CREATE TABLE INTERESSE_TAG (
  TD_TAG INT,
  ID_USUARIO INT,
  PRIMARY KEY (TD_TAG, ID_USUARIO),
  FOREIGN KEY (TD_TAG) REFERENCES TAG(TD_TAG),
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

-- Tabela LogsPaginasSite
CREATE TABLE LOG_PAGINA_SITE (
  ID INT PRIMARY KEY,
  SESSAO_ATIVA INT,
  TEMPO_DURACAO_SESSAO DOUBLE,
  DATA_SESSAO DATE,
  QTD_NOVA_SESSAO INT,
  TOTAL_VIEW_PAGINA INT,
  LOG_PAGINA_SITECOL VARCHAR(45)
);